### ISSUE TITLE
Biomes

### ISSUE THREAD

**Issue by GothkittyGirl** [BentoBoxWorld/Boxed#23]
not all biomes generate in the world. ik only one for now because i have 25/42 and not sure what biomes ive found. but the one ik ive not seen is ice spikes

**Comment by tastybento** [comment]
So, you are playing Boxed?

You are correct, not all biomes generate in the world. Ice Spikes are there though, at the edge of the island bordering the sea. You can edit the box world to enable more biomes by adjusting the Boxed/biomes.yml file. But be careful doing this mid-game because you might create some abrupt changes in geography.

Here is the first part of the file:

```
# Change these mid-game will only affect newly generated chunks, so be careful!
distribution:
  overworld:
    north-east:
    - 0.05:PLAINS
    - 0.1:DESERT
    - 0.2:SAVANNA
    - 0.4:JUNGLE_EDGE
    - 0.5:JUNGLE
    - 0.6:JUNGLE_HILLS
    - 0.75:BAMBOO_JUNGLE_HILLS
    - 0.8:BAMBOO_JUNGLE
    - 0.9:BADLANDS_PLATEAU
    - 1.0:BADLANDS
    - 1.1:LUKEWARM_OCEAN
    - 20.0:WARM_OCEAN
 ```

The box is divided up into 4 quarters - north-east, north-west, south-east, and south-west. For each quarter there is an entry, for example:
`- 0.2:SAVANNA`

The number is the ratio distance away from the box center. 0.2 means 20% of the overall box size. This number can be bigger than 1 because the corners of the box are further away from the center than the edges of the box. So:

```
    - 0.05:PLAINS
    - 0.1:DESERT
    - 0.2:SAVANNA
```
This means that the center of box up to 5% radius will be PLAINS biome. Then from 5% to 10% will be DESERT. Then from 10% to 20% will be SAVANNA, etc.

You can add more biomes into the list. if you make the difference too small between entries then the biome might be very small.

I realize this is complicated. Unfortunately, I don't think it will be possible to add every single biome because there are so many now. However, you can change or add them if there is one you really like.
