### ISSUE TITLE
Found bug associated with chatcontrol

### ISSUE THREAD

**Issue by TaminoPalm** [BentoBoxWorld/Boxed#29]
When you have chatcontrol, and write yourself a private message, a toast message appears, this is normal, but with boxed, your box gets bigger on every new message

Here a photo: https://ibb.co/R9mtxFD

**Comment by tastybento** [comment]
In `advancements.yml` change it so that unknown advancements receive zero points:

```
# Lists how many blocks the box will increase when advancement occurs
settings:
  default-root-increase: 0
  unknown-advancement-increase: 0
```

ChatControl appears to be using the Advancement feature to generate these toast messages. So, it is incompatible with Boxed and not a bug in Boxed. 

By making the change above, you will have to manually list all custom advancements in the advancements.yml file if you want them to give you an increase to your box.
