### ISSUE TITLE
Custom advancements not work

### ISSUE THREAD

**Issue by DeltaX86** [BentoBoxWorld/Boxed#61]
### Expected behavior

When the progress is accomplished the box should expand by the chosen number.

### Observed/Actual behavior

The advancement is not detected, and border not change
The directory IslandAdvancements in database directory not created
But player Advancements exist in world directory

### Steps/models to reproduce

[datapacks.zip](https://github.com/BentoBoxWorld/Boxed/files/13180519/datapacks.zip)
[advancements.zip](https://github.com/BentoBoxWorld/Boxed/files/13180521/advancements.zip)

### BentoBox version

Running Invalid (PUFFERFISH) 1.20.1.
BentoBox version: 2.0.0-SNAPSHOT-b2474
Database: JSON
Loaded Game Worlds:
boxed_world (Boxed): Overworld, Nether
Loaded Addons:
BentoBoxFAWEHandler 1.1.0 (ENABLED)
Border 4.1.1-SNAPSHOT-b185 (ENABLED)
Boxed 2.3.1-SNAPSHOT-b242 (ENABLED)
Challenges 1.3.0-SNAPSHOT-b531 (ENABLED)
Chat 1.1.4 (ENABLED)
ControlPanel 1.13.1-SNAPSHOT-b61 (ENABLED)
InvSwitcher 1.12.0-SNAPSHOT-b230 (ENABLED)
IslandFly 1.11.1-SNAPSHOT-b165 (ENABLED)
Level 2.11.0-SNAPSHOT-b541 (ENABLED)
Likes 2.4.0-SNAPSHOT-b97 (ENABLED)
Limits 1.19.1-SNAPSHOT-b318 (ENABLED)
RoseStackerHook 1.0.0 (ENABLED)
Visit 1.7.0-SNAPSHOT (ENABLED)

**Comment by tastybento** [comment]
It does work, but the advancements.yml format is as follows:

```
# Lists how many blocks the box will increase when advancement occurs
settings:
  default-root-increase: 0
  unknown-advancement-increase: 0
  unknown-recipe-increase: 0
  # Scores based on proprietary algorithm. If false, each advancement is scored manually
  automatic-scoring: false
advancements:
  'building/clay_have': 10
  'building/brick': 15
 ```

So, don't put "bentobox:" on the front.
<img width="465" alt="Screenshot 2023-10-26 at 11 41 02 PM" src="https://github.com/BentoBoxWorld/Boxed/assets/4407265/8894e451-69ae-4595-82ed-6e98b156c71e">

Also, the zip file [datapacks.zip](https://github.com/BentoBoxWorld/Boxed/files/13180519/datapacks.zip) is not a datapack file, so it won't work. But maybe you know that. If you use the BoxedDataPack.zip file, then it will.
