### ISSUE TITLE
Advancement Manager

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/Boxed#7]
#### Is your feature request related to a problem?

When player's create a new island, it resets their advancements via the Mojang command, which spams operator's chats, and is impossible to disable without entirely disabling command output

#### Describe the solution you'd like us to implement.

update https://github.com/BentoBoxWorld/Boxed/blob/develop/src/main/resources/config.yml#L333-L368 to include:
```yaml
    on-join:
      reset-advancements: true
      grant-advancements: {
      "minecraft/story:root": true
      }
    on-leave:
      reset-advancements: false
      grant-advancements: []
```

#### Describe alternatives you've considered.

Doing it via commands.

### Additional context

N/A
